language: python
python:
- '3.6'
services:
- postgresql
env:
- DJANGO=2.0 DB=postgres
global:
- PGPORT=5432
before_install:
- cd decide
- cd decide
- cp settings_ci.py settings.py
- cd ..
install:
- pip install -r ../requirements.txt
before_script:
- cp local_settings.example.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- psql -c "alter user decide createdb"
- python manage.py migrate
- python manage.py makemigrations
- python manage.py migrate
script:
- python ./manage.py test
after_success:
- cd decide
- cp settings_heroku.py settings.py
- cd ..
- cd ..
addons:
  postgresql: '9.6'
deploy:
  provider: heroku
    api_key:
      ortosia-votacion-prepro:
        secure: DuWPdYIpFLrUXdfnMu7cHIlXnJDyIGxNBKg9V4YMcKWJ2aN9iBx0u3YsJu3vSHHr37RegDdmXzVFu5BxGwdPrKGoI/TpwzXOpNXiJx9zlU/7q6DBmeXMh5Uv+WjmBV15RBeC9U+78dz3Z0Z8yiSRrGSpaUdvpLmNHzrziFnJbyPXh0LOGwMzRzzubQBwWDOIAfAVppnOGYJt6vQrSvGX6elUMjonENm2OCJ0Spl23v6vJrRagMqOt+jUx/hX43n16EJnjByTYrhSfk+3f3r05CcG7EqyAj7vBUp4Q/kl1VJvkg87px3CYp6fBJjZgGX9zVn6A2SlcdnzrwuXRtvQr9It+LWkzxqRiRiNswB6oknD3p8O+Ye2Uc03rcp0H29mKa/1oTdRkM6W8Vm3jv9l4xCvdkGX2H18+VzO6lrRlYZkiPM22YS1dAhQpW15FMjnGjf1I+KjbIJw9WQJERHl2JGWrVLQ6VkMN2V3FaI18pbSLM5QYLRpdCSjNatwAMSaTYcvphkbvp2+DtArvP9vJe7ghW8MxEZCVLx8ctfonSHrnAdOJQZiY7R7PT45bPiybzmab/U8R02/mbEoOOmOcTxGEstM4Bkg8CzW+qe/ntyGM67J0yrjMO3p9RQNklYQ8fiy4fsUhmbEGBFrq0WC0MsrIlB0i1m5OTtAs5ouyEo=
  app:
    ortosia-votacion-prepro: decide-ortosia-votacion
  skip_cleanup: true
