language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
sudo: required
services:
- docker
script:
- cd docker
- docker exec -ti decide_web ./manage.py test
- cd ..
addons:
  sonarcloud:
    organization: pablotabares-github
notifications:
  email: false
before_install:
- cd docker
- docker-compose up -d
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: vTih8kRj2WO0smoYyHps2Z1huW0ZZ2P0XhNg5muiy5zCyY/k6Vew9bOfYfDZfYAE2aKeWJm2WanftyYn/ybPz8WBTehEj1XPbWGdTwa4SA9RsKtoEsxboiWmAc5tV/7pBI7C3aTYMyyZzFH3WsXSW+nZk68n+3C7S/7pSiNp34UFtOefIhVxX2uH5TTes7RknyB1Rzg14KfbAQQ+UTh8rpgoaIe2MuIgv0jlx3CIPpPwqMbuyTDVktoOBecPatHRsWFrUdu2IJuGxKwoHROYbwAZmxuVuDbg9jFJWEPVzDpA8nItDpK6f/dx0lb+YDE58tYnYJkiW7IxTc2AoWZrbD2s2cZF2VnrzM54SE5laVpbf2N3LeeyqdOQqiTS5Oigh4q6GvyxICoAdDkFeCHi2WWTvcCzJJVPe4OMgpyoLE/1B3ta2l/ljmQCWjafB+JX1WY2Cy0M5FNA+7bwFvEwuhzK2lmLtn4DiM/kbYIMUVr7fLjh1xHUJ+aylrIPAfgBcekj5hF62sYaU7DGMtX15OD8tn8HCp2uyY3aTWBY6T/95Oc966IT29L3HBdCITJMQqmn9qizn9bg3u7A6AFgwd//Ka4EnknhNk0Gpzj0PJ0UaoHQwzcGwZa43kd+uOWW8BEF66WxoRZLZpVIkoV9nG96V97oHkwHpBn5IS8ovYA=
  app: decide-ortosia-visualizacion
  on:
    repo: pablotabares/decide
    branch: ortosia-visualizacion
