language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
sudo: required
services:
- docker
script:
- cd docker
- docker exec -ti decide_web ./manage.py test
- cd ..
addons:
  sonarcloud:
    organization: pablotabares-github
notifications:
  email: false
before_install:
- cd docker
- docker-compose up -d
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: 6mCEeq0SYfxe/gcnN6e1oM+KYdzKcgQ7y34VhGHOfRvHpwrfnz0l5TOQ2UDg1QlGNjF9Odg3P6x0nMMzrTn0OcMf6cBlfrM6LovkTkjrtlOrL37TkPJxCiFtQHNkoMxOYMXCgHq0+HPo1reUWLioByfi+ZQdU1bh2OuzdSL/NNN5WoSE5SbYZV7U723mco/0yRxP6I+tlY4xcqmcW4OhPYFOzZ393h4kZiteKwyKn13uOtbgvU0h5I7mqlt/mi6BfaSXnTlRrD2KKKqYTAoe99M9fs7lUDtCw7Wjn5hSIL+qz2x28HQDpn273U9CniotA2+1IS5krggd3FpdBDf1V6zcBL3sSmxhsgzWfGwnWnl3dxvVzhvzU/3MZkI/sZld4xwGH0AN813jfiPZSm6Iknbwd9GxNj0vB+lhl7wtFcmvZwbJJeFMjg5dT6E9SRSO1Hw9FCZoa2CUsJgYub8UCVgC2Pa/JAm976j/V0PqdZJGjpBxe79fZW/0SKX2qgQeLFJQj8LI6Hv90MBbjpRlfAx236HkGQ+olZkzXtg0N0YFUmrXnclByYUBF7HQ538QqtHYMyMeYpLcCj4QF17MCBbcf8rWOaHQLY8fr32ZdQugKwPDX1fA6TYqYhWd0hjeMF7OUHGtyn7xL+VymPsLKKIX/UD5NaUfqcqKwU4vXtQ=
  app: decide-ortosia-censo
  on:
    repo: pablotabares/decide
    branch: ortosia-censo
