language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
sudo: required
services:
- docker
script:
- cd docker
- docker exec -ti decide_web ./manage.py test
- cd ..
addons:
  sonarcloud:
    organization: pablotabares-github
notifications:
  email: false
before_install:
- cd docker
- docker-compose up -d
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: Bo4c6BVusUP/rbtEG/3Y0mV85XlNyWCdGKVRte6hcqPi6lPmvXO+aQpGFSfRbuEsDXrtAh6T139eJ8owxOuL4XNNyakKNmiPyek2osQ9ivl5hWb2NGUBUlw9EmiYT1MWdKVb/iwzhuPZ8iwaHoJ3iAVge1c5yfmp0tDZ7IZT/h12JNQ5YSHnBamjlmfE6OKbaspObiOerASwUM95udjDoHZ1+sqcp9TOWJy9jSbK3uZnPd0gQYxPXjEVo8d0xQZVMuP8PG9apcp+Hmh5eI8alNy2zenOhdnlHd/1Sj+10RxL0LbeCKNNi5ZWJepins/dcdY879f73Waz9fCRNARdbx/ofPpHuidBodkLm72pkxHNFD6aG1nPMG6LbLcyoqAW+cajBPnyJshHPVN2+TB7WRs2R/kGdPlXIXd0p1SdACuxxGnaG8kJGbwf5nQN0ya01PnXTAotelJvcmF4T2EUOg+d4osD6S3N3dMreu6Tfp+8Q/zR+LqkORBzlN/aCNzkQPCHeLgVT+avRzMl9WZGhpXoZjhcefnTz+WvqVztd0PjLXZE3fptda2hoePDk3kthjVFt0eYFyG/R/WCPo7xZG4j8gXflMJ1WqMnXvQ4t4n4OoczwbK+Okjr/R8VkD5ATf447z6q117YrwAv+PApeDnZxn4YJWAo5uu31kOR/KQ=
  app:
    ortosia-visualizacion: decide-ortosia-visualizacion
