language: python
python: 
  - "3.6.6"
env:
  - DJANGO=2.0 DB=postgres
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD_CABINA" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
install:
  - pip install -r requirements.txt
before_script:
  - cd decide
  - cp local_settings.example.py local_settings.py
  - psql -c "create user decide with password 'decide'"
  - psql -c "create database decide owner decide"
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - cd ..
  - sonar-scanner
  - cd decide
  - coverage run --source=. manage.py test
  - coverage report
  - coveralls
  - cd ../docker
  - docker build -t ortosiacabina/decide .
  - docker tag ortosiacabina/decide registry.heroku.com/cabina-ortosia/web
  - docker push ortosiacabina/decide;
  - docker push registry.heroku.com/cabina-ortosia/web;
deploy:
  provider: heroku
  api_key:
    secure: 3e21549d-a76b-40d2-8bd2-c3840b015279
  app: cabina-ortosia
  on:
    repo: pablotabares/decide
    branch: ortosia-cabina
sudo: required
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
  sonarcloud:
    organization: "pablotabares-github"
global:
  - PGPORT=5432
notifications:
  email: false


