language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
sudo: required
services:
- docker
script:
- cd docker
- docker exec -ti decide_web ./manage.py test
- cd ..
addons:
  sonarcloud:
    organization: pablotabares-github
notifications:
  email: false
before_install:
- cd docker
- docker-compose up -d
- cd ..
deploy:
  provider: heroku
  apy_key:
    secure: d7W0yMnRwRstu04b7vtPodlz8ZPOgIPG0Zxt9T1csG7sDLipsBauYoA+BKIvTlWflXT6fvAgZoE7HR++uYlrWcDvFuD+t/bKxZGyOy+CvHs/U9ZT401+iA9J/Q8WeG26cVAgmfNsUuVLoXqzPpPaXb7y55fXI608GvdzXuRj3iltkL1LG1IcNQhwBb87eFNdaWT3GYMNibv0TGa4D9OmZ0UiLrFj9bj12Ljn8LRSB6Uv/rUH4hZomdvdtxxErQbooRjRmqedCiQOZe8D3lqazFT3LSuBIoVTsas/y8O2IsJx8kw3iaJajHTW2oCz77SGWBGmKXFI+YY6AoEB8eFL1gHd5gCSseT68tZOVF7g8T+SXCKnyvD5RD3I/OCRfCIfxi+Mho3vi055/1IY8+t+H1KJcqxGS1Hp9MAVy9vscpRgxLYDd6DTamNfitDX3xKu49jOef24VfsqXdoVVlRuqkV1Dy1PY3SevVzfERx0fX3TYGgffNTP3e2mwe2OGqp6pNVX8N2Y2TPTAfLe6CZuo6cCTrhwcVVLIiJEJFqJxB1nJAOQEUNWnwGNWXCQTSgL0f1vg7JQm8mhT7fp1nqhV3FU1Zi58mlYY5/HJbr4NnOBDavHIyqBiXM6YLoHkqyoE4NP3nL4QF5uo1PgOQBOohI/M1OHN1JEmiUntJdL2R0=
  app: decide-ortosia-visualizacion
  on:
    repo: pablotabares/decide
    branch: ortosia-visualizacion
  
