language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
sudo: required
services:
- docker
script:
- cd docker
- docker exec -ti decide_web ./manage.py test
- cd ..
addons:
  sonarcloud:
    organization: pablotabares-github
notifications:
  email: false
before_install:
- cd docker
- docker-compose up -d
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: vYQiy5P27LL4fUiqm25n4+2wo3Xrv9/z8jZ/dM4x/hbDS+McC2Dwksaa6jE7zXAnDHpbSZqP6JOB2/ZCnbTBqUxhwycGZ5Q8eZLXaS19sXOGfxMZ20SJao4hRiwxR8KLsZkLiw9kJP2lF5iO67R//bTDNYPXtQn1Dzko6EF1IePsuAE+QuC6zhinTlEi9RKWo012/8851I/uEtLijSq0JtpjBks1uNeYgRZ5zpsPLb/xmQzTOvW0irdYPKYlHilkrMYUKSnE76iSJTsHMsn4hVPa+RJVxWELMcnjeAVe6yJxpfRosLL6U1dYCkb147RnL4yRUUDiozF0zrKCcu0I/semd0siNg1LS3vmI4DiJub5CdGbNu8HZtfwu86udZwoD45KY/RNeMuK0/h2fdAr+BiMkc/7UyHVq2KtZNzKdweFlfBeklALSd6ovSfsLJln2QWDhyX0zIKIfW3ssQy3lB909wmS+jxJ6Uz00KHVl9uuLJF4hPFMNoX4QJywAG5srVCA3JlGhw8RtWD/AXQH5fcspkL8zJhSqGlH1W2McEuyGCUSx8O9rn7ILf0Cg7N8vc/+O7T8huR0ZJ8JW9f4u0QIL+kcEz7QIpJ7aw+ARXvnmoqi4orWDrXtscg9OCm9qViDUkribdzYSc5xuYzUYe5fQk9HRav0LZ62nrduVNE=
  app: decide-ortosia-visualizacion
  on: ortosia-visualizacion
  skip_cleanup: true
