language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
sudo: required
services:
- docker
script:
- cd docker
- docker exec -ti decide_web ./manage.py test
- cd ..
addons:
  sonarcloud:
    organization: pablotabares-github
notifications:
  email: false
before_install:
- cd docker
- docker-compose up -d
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: 5/2t/3EdPj7uYTHbeth9PzNVzKL8rJf6B8hnuhO6Ns6wVzrgrKKLdSikujlRG5HSOtybvMaeCECcrc6E4J/JvgIszvkFQXFLMp3+8Dx4H9fuKheWxT8T2ZRq8t+H0Jxr9L1d4iLmZj1yH65/9YAGE1ZT5OnHeqlyHaGwSvI2PaAi+U3tDSkrsXuUTB5DbdvhLRu/Pi3si3+Y6p71aQJs95FbC0y3jrvDO00Ejeb8JWN5CyVyGTlQ/fH3rHAizWhRhybH92yfl+KupI99d3HtlAZymRqh2o3oZ2FvF901LA9q0UCC2Wpn5/EWkzXhxEUyYT9xbYtJTi+JyOFQh+kGqRNp9jMq+u3XForqjm+9iLnm038Io/JxPWKyYkUyS+N7zJXO/kLj71y5pk3tbrMz3mdDVUspi+FTYknXI3fHhyWUt5PZMapOX4yUAhXBjhkHpTp2+/4gi59h0L4uEvSXmz2yncD3c9SXzJb5/V0148FgRav8CP0qA3hIb4kLcblhSepUZH9sDGPwXbvcnTUoiKx7GFrVgqhyTucPNT79O/4TF0wFwJJjaq/N/8EteuusL8i7wLcPNXz/S/B5xFbssUi3x3QMgyY2/P7dCU4pFiUa9XgAm3fCqlaUDMwSpEhd1Qtfj+M2gtHWor0bKl1utxTvH1hlsZS7DvwwB0nXFWE=
  app:
    ortosia-visualizacion: decide-ortosia-visualizacion
