language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
sudo: required
services:
- docker
script:
- cd docker
- docker exec -ti decide_web ./manage.py test
- cd ..
addons:
  sonarcloud:
    organization: pablotabares-github
notifications:
  email: false
before_install:
- cd docker
- docker-compose up -d
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: 7neAyqye0RwVFePRAY6a0jP9g95xGW+3EEPrrZWWj+2PiSgj3a93QgR67AO1L9BFVyl82+dCqfFDey2/V1ZEZmYcytBiNLpKigxT/ug6YSuWoBrEhmTtF5M4dfAGkE+fmyYcWDwT8hpE5zfsn8V6FI/Dkb+eGVjjxadmbEIzoZryn4HGNNeEVKQAyBenUHOj8Mui3gOTpmyex2UFDDVUg2M1Lk+MUE79RGBBRZGQXDki2BVbEwNO3NJQuWvQyje/6C0DZ5NEv1WxtpUktV3a7JGQK+Tqm1Ui1tm650eV5j/hvPunpnuL4L9plQKo4MROILXEF37YJ2ZDWn83h3jFxxQ8eU5FUk1OBwegNezWa0Q1NXbMzyt8wikV3daDFVi5/Wh2agjsCWQOpYoTcAiHND9AShte6e/2rPFgP+F7MDTIS6SeV8BgfsOmB5H4/5oV4e+yna1LZZisqf8tZ/vTTKklLjineh5yV9HAXO5O4EJqMkmJF2WDrravLFVOsXB+yL7e/4CN7cWIacrNirCLck/j20xvtBrMIYrQc1xA7FpEIaLSXIv1PEAhvzrG8MaaScj3Ys4IqMDb7KqZuj6wX8sskvYL37IBNjzVyHjR9zOIq8/4AKWboT6u9a1XmxeKFR72f4tfb8LxRufut1z0Zq/XHlLO78TUDMAvxryoKHE=
  app: decide-ortosia-visualizacion
  on:
    repo: pablotabares/decide
    branch: ortosia-visualizacion
